### ISSUE TITLE
Render the training shapes with camera poses

### ISSUE THREAD

**Issue by fbhdr** [3DTopia/LGM#15]
Thanks for the great work. I wonder whether you can provide the rendering script for creating the training dataset. If not, is it possible to provide a sample training shape with camera poses (e.g. 1 or 2 samples)?

It seems that the camera poses rely on the definition of "opengl world" from this [link](https://github.com/3DTopia/LGM/blob/45a9b39ad38d758472c70da01778e1ec06823934/core/provider_objaverse.py#L94C46-L94C64), and the definition of [proj_matrix](https://github.com/3DTopia/LGM/blob/45a9b39ad38d758472c70da01778e1ec06823934/core/provider_objaverse.py#L52) is different from the original 3DGS paper: [link](https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/utils/graphics_utils.py#L51). (There seem to be a transpose?) These differences seem to cause different processes of computing the `cam_view` from [original 3DGS](https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/utils/graphics_utils.py#L38).

Typically the camera poses describe the relative transformation between the camera coordinate and the world coordinate. Do we have to manually define the world coordinate here? Under your code framework, what is the "world coordinate system" definition of original 3DGS?

**Comment by ashawkey** [comment]
@fbhdr Hi, sorry that the dataset is not rendered by me, and I don't have their rendering script.
But as far as I know, our dataset is similar to [G-objaverse](https://github.com/modelscope/richdreamer/blob/main/dataset/gobjaverse/README.md), and I recommend to use their data directly.

3DGS use OpenCV camera convention, while we load the camera into OpenGL camera convention. (For more details you may check https://kit.kiui.moe/camera/). Actually the proj_matrix is the same, they transpose it later here: https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/scene/cameras.py#L55

The world coordinate system of our dataset (also G-objaverse) is in blender format, so we transform it into OpenGL format here: https://github.com/3DTopia/LGM/blob/main/core/provider_objaverse.py#L94

**Comment by FangjinhuaWang** [comment]
Hi, thanks for your great work. I also have some questions about the camera transformation since i am not very familiar with OpenGL, NDC. I understand that you already transpose the projection matrix to clipped space [here](https://github.com/3DTopia/LGM/blob/45a9b39ad38d758472c70da01778e1ec06823934/core/provider_objaverse.py#L52). But i do not know why only 5 elements are non zero, while 3DGS has 7 (actually, there should be 7 non-zero elements as discussed [here](https://www.songho.ca/opengl/gl_projectionmatrix.html)). Another question is why there is a minus [here](https://github.com/3DTopia/LGM/blob/45a9b39ad38d758472c70da01778e1ec06823934/core/provider_objaverse.py#L166)?

**Comment by ashawkey** [comment]
You can check the last matrix in the second link, two of the elemets are 0 for cameras with centered focus, which is the usual case.
The minus is simply due to the implementation of the diff-gaussian-rasterization renderer.

**Comment by FangjinhuaWang** [comment]
For the first question, yes, you are correct. these two values should be 0 in most cases. But i have another question about these:
```
self.proj_matrix[2, 2] = (self.opt.zfar + self.opt.znear) / (self.opt.zfar - self.opt.znear)
self.proj_matrix[3, 2] = - (self.opt.zfar * self.opt.znear) / (self.opt.zfar - self.opt.znear)
```
I think they do not normalize z range into [0,1]? But something like [near^2/(far-near), far^2/(far-near)? In 3D GS, it is like 
```
P[2, 2] = z_sign * zfar / (zfar - znear)
P[2, 3] = -(zfar * znear) / (zfar - znear)
```
which correctly normalize [near, far] into [0,1].

For the second question, in gaussian splatting code, what I found is that the camera_center (last row of c2w, [link](https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/scene/cameras.py#L57)) is used as input of [rasterization](https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/gaussian_renderer/__init__.py#L46). so there is no minus. Did I miss anything?

**Comment by ashawkey** [comment]
@FangjinhuaWang 
1. Actually I'm using the formula in the link you provided... in any case, znear is a very small value and may have little impact.
2. You may notice their code uses `view (w2c)` instead of `pose (c2w)` matrix. Since `pose = inverse(view)` and we are assuming an orbital camera, there should be a minus.

**Comment by FangjinhuaWang** [comment]
Thanks for your reply! In 3DGS, I think the ```view (w2c)``` you refer to is ```world_view_transform```, right? I think they inverse it into ```c2w``` when computing ```self.camera_center = self.world_view_transform.inverse()[3, :3]```.

**Comment by ashawkey** [comment]
Oh you are right... their code is really involuted. 
However, I remember the minus is necessary for correct rendering. Maybe you can test it by yourself!

**Comment by FangjinhuaWang** [comment]
Thanks! I will have a test when I have [G-objaverse](https://github.com/modelscope/richdreamer/blob/main/dataset/gobjaverse/README.md) ready.

**Comment by insomniaaac** [comment]
hi, i still confuse about the transformation from opengl to what needed by gaussian renderer
```py
# opengl to colmap camera for gaussian renderer
cam_poses[:, :3, 1:3] *= -1  # invert up & forward direction
# cameras needed by gaussian rasterizer
cam_view = torch.inverse(cam_poses).transpose(1, 2)  # [V, 4, 4]
cam_view_proj = cam_view @ self.proj_matrix  # [V, 4, 4]
cam_pos = -cam_poses[:, :3, 3]  # [V, 3]
# c2w is inverse of w2c (cam_view)
cam_c2w = torch.inverse(cam_view)
```
1. why transpose(1, 2)?
2. why minus? if it is just necessary, ok, skip that.
3. can i just inverse cam_view to obtain cam_c2w?
