### ISSUE TITLE
Questions about the image-to-3D inference process

### ISSUE THREAD

**Issue by TLB-MISS** [3DTopia/LGM#16]
@ashawkey @brentyi Thank you so much for the great work!

Is there any process for estimating the azimuth and elevation of the input image in image-to-3D Inference? As a result of experimenting with several instances, the output mesh (or pointclouds) was often produced by correcting the elevation or azimuth of the input image. However, this process is very unstable.

1. Is there a process for correcting the elevation and azimuth of the input image?
2. If such a process exists, does it try to correct the elevation and azimuth of the input to 0 when producing output?

Thanks

**Comment by TLB-MISS** [comment]
What is certain is that the azimuth is adjusted. I hope that the model does not correct azimuth (since it is not robust). Is there no way?

**Comment by Colezwhy** [comment]
> @ashawkey @brentyi Thank you so much for the great work!
> 
> Is there any process for estimating the azimuth and elevation of the input image in image-to-3D Inference? As a result of experimenting with several instances, the output mesh (or pointclouds) was often produced by correcting the elevation or azimuth of the input image. However, this process is very unstable.
> 
> 1. Is there a process for correcting the elevation and azimuth of the input image?
> 2. If such a process exists, does it try to correct the elevation and azimuth of the input to 0 when producing output?
> 
> Thanks

Hi, have you found any methods with this? I am facing the same problem too.
