### ISSUE TITLE
Question about inference

### ISSUE THREAD

**Issue by TLB-MISS** [3DTopia/LGM#17]
@ashawkey @brentyi Thank you so much for the great work!

I have a question about the camera setting during inference.
In LGM, ImageDream is used to infer 4 images for camera settings with an elevation of 0 degrees and an azimuth of 0, 90, 180, and 270 degrees from the input image.

However, inference about the elevation and azimuth of the input image sometimes succeeds and sometimes fails, so for each instance, some inputs produce output that is canonicalized (output facing the front), and some inputs produce output that looks in a different direction.

I want to resolve this instability. Is there a good way?

I think this problem is because LGM uses absolute camera coordinates(for ImageDream?) rather than relative camera coordinates. Is it currently impossible to assume that the azimuth of the input image is 0 degrees and infer it based on relative camera settings?

**Comment by ashawkey** [comment]
@TLB-MISS Hi, thanks for your interest! Actually we do assume the first image (out of the 4 provided) is at azimuth 0 during training. However, ImageDream cannot stably generate canonical views of the input image. 
I guess a possible solution is to use better multi-view diffusion models (like the recent [eschernet](https://github.com/kxhit/EscherNet), [SPAD](https://yashkant.github.io/spad/), and [IM-3D](https://arxiv.org/pdf/2402.08682.pdf)).

**Comment by TLB-MISS** [comment]
Thank you for your answer!
