### ISSUE TITLE
GS rendering is not Incongruent with the input image

### ISSUE THREAD

**Issue by fefespn** [3DTopia/LGM#19]
Hey,

First I want to express a big thanks! your work/ideas/paper/time/code and generosity are truly appreciated!

I noticed this thing:
The experiment was to check if the GS exactly matches the 4 input images. (by "matches" I don't mean the rgb/resolution, but the size/perimeter/mask of the object)

So the experiment was like this: I took the GS from the U-net (before even fitting a nerf), and then I rendered the GS to see if the rendering (from the same positions ofcourse) matched exactly the 4 input views.
I put the rendered images and the input images on top of each other (and the masks also), and yes, I saw a little bit of mismatching.
From the test I made, the mismatch was in the perimeter of the model. The GS  is a little bit smaller in perimeter.

My goal is that in the end, I want to get exactly the same size/perimeter/mask as the input images.
So I want to ask:
From your experience, which one of these options you would go first:
1. After fit_mesh, add a new optimization iteration called fit_mesh_to_input_views, and in this optimization iteration optimize the deform/normal/rgb just for the 4 input images ? 
2. In/During/With the fit_mesh optimization iterations, optimize also on the 4 input views ? (so one iteration on the GS rendering the other on the input images....)
3. Building a new optimization function, we call it fit_gs, that does the same optimization on the GS as the training, and call this function before fit_nerf ? 

Thanks a lot,
Firas

**Comment by ashawkey** [comment]
@fefespn Hi, it's strange that there is mismatching in perimeter... since we do optimize the input views during training with MSE.
Could you check the camera parameters or show some examples?

**Comment by fefespn** [comment]
Oh ok I understand your point, my example is from real image so I don't know the exact focal length of the camera, so you say this might be the reason for the mismatch ?

**Comment by ashawkey** [comment]
Yes, this is possible.

**Comment by ashawkey** [comment]
Yes, since our training dataset is only rendered with a fixed fov of 49.1.
It seems the current best practice is to fix all intrinsics and only change elevation & azimuth (radius is fixed during training too...).
We have some augmentation to the image and camera extrinsics, but none to the camera intrinsics.

**Comment by fefespn** [comment]
Ok thanks a lot ! Appreciate your time.
