### ISSUE TITLE
AttributeError: module 'pymeshlab' has no attribute 'PercentageValue'

### ISSUE THREAD

**Issue by zhizdev** [3DTopia/LGM#2]
Thanks for the code @ashawkey ! This is awesome! 

I am running convert.py (and thanks for the updated kiui), and now I am running into an issue with this: 

```
Traceback (most recent call last):
  File "/home/~/code/lgm/convert.py", line 460, in <module>
    converter.fit_mesh()
  File "/home/~/code/lgm/convert.py", line 294, in fit_mesh
    vertices, triangles = clean_mesh(vertices, triangles, remesh=True, remesh_size=0.01)
  File "/home/~/miniconda3/envs/ldm2/lib/python3.10/site-packages/kiui/mesh_utils.py", line 127, in clean_mesh
    threshold=pml.PercentageValue(v_pct)
AttributeError: module 'pymeshlab' has no attribute 'PercentageValue'
```
My current pymeshlab version is: `pymeshlab-2022.2.post3` and I installed it with `pip install pymeshlab`

I am on python 3.10

Would love any insights or feedback on this issue!

**Comment by zhizdev** [comment]
Thanks @ashawkey ! 

I wasn't able to install the latest version of pymeshlab for some reason despite trying for a long time. 

I solved this by installing kiui locally and modifying mesh_utils.py by adding a monkey fix (in case anyone else experiences the same issue). 

```
if PML_VER == '2022.2.post3':
    pml.PercentageValue = pml.Percentage
    pml.PureValue = pml.AbsoluteValue
```

**Comment by ashawkey** [comment]
@zhizdev Thanks! Would you like to open a PR to add this to kiuikit?

**Comment by zhizdev** [comment]
Thanks, opened a PR.

**Comment by Justinfungi** [comment]
> Thanks @ashawkey !
> 
> I wasn't able to install the latest version of pymeshlab for some reason despite trying for a long time.
> 
> I solved this by installing kiui locally and modifying [mesh_utils.py](https://github.com/ashawkey/kiuikit/blob/main/kiui/mesh_utils.py) by adding a monkey fix (in case anyone else experiences the same issue).
> 
> ```
> if PML_VER == '2022.2.post3':
>     pml.PercentageValue = pml.Percentage
>     pml.PureValue = pml.AbsoluteValue
> ```

Yup this monkey fix does help. It seems the pymeshlab 202312 post failed the test and cannot be installed.

**Comment by brabbitdousha** [comment]
> > Thanks @ashawkey !
> > I wasn't able to install the latest version of pymeshlab for some reason despite trying for a long time.
> > I solved this by installing kiui locally and modifying [mesh_utils.py](https://github.com/ashawkey/kiuikit/blob/main/kiui/mesh_utils.py) by adding a monkey fix (in case anyone else experiences the same issue).
> > ```
> > if PML_VER == '2022.2.post3':
> >     pml.PercentageValue = pml.Percentage
> >     pml.PureValue = pml.AbsoluteValue
> > ```
> 
> Yup this monkey fix does help. It seems the pymeshlab 202312 post failed the test and cannot be installed.

same issue
