### ISSUE TITLE
Strange tail

### ISSUE THREAD

**Issue by emailandxu** [3DTopia/LGM#21]
When uses image to 3d there're tails in the animals or human like shape, why will that happen? Could you please give some clues to explain this phenomenon?

![Snipaste_2024-02-20_17-47-37](https://github.com/3DTopia/LGM/assets/11490462/d823b866-f1e9-43e0-b723-ecfc159c8692)

**Comment by ashawkey** [comment]
@emailandxu Hi, that's typical for the multi-view images generated by ImageDream, maybe due to the bias in their training dataset. You may try other random seeds, which may not have such tails.
