### ISSUE TITLE
no file named config.json found in directory ./pretrained/image_dream？

### ISSUE THREAD

**Issue by harryzhu123** [3DTopia/LGM#41]
/home/hairui/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/hairui/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/home/hairui/.local/lib/python3.8/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/data/zhuhairui/LGM/core/attention.py:22: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/hairui/.local/lib/python3.8/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/hairui/.local/lib/python3.8/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
[INFO] Loaded checkpoint from pretrained/model_fp16.safetensors
Keyword arguments {'trust_remote_code': True} are not expected by MVDreamPipeline and will be ignored.
Loading pipeline components...:  29%|████████████████████████                                                            | 2/7 [00:00<00:01,  3.64it/s]
Traceback (most recent call last):
  File "infer.py", line 58, in <module>
    pipe = MVDreamPipeline.from_pretrained(
  File "/home/hairui/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hairui/.local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 819, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/hairui/.local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 476, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/home/hairui/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hairui/.local/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/hairui/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hairui/.local/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ./pretrained/image_dream.

Its hard to connect to huggingface in mainland of china, so i download all the pretrained weights of ImageDream from huggingface, but seems there is no file named config.json in huggingface repository:

![image](https://github.com/3DTopia/LGM/assets/44469501/8b9788c0-4fb7-4ee2-a2db-8b861db1d999)

whats the problem?

**Comment by Oqyriel** [comment]
Hello, is this problem solved? I'm also experiencing the same problem, can you please tell me how to solve it?
