### ISSUE TITLE
Question about train_pred_image and eval_pred_image at finetune time

### ISSUE THREAD

**Issue by yisuanwang** [3DTopia/LGM#44]
Thank you for your wonderful work! However, I have a question about the fact that in finetune, both train_pred_image and eval_pred_image only have output on the far left side; the right side is blank. But both GT images are normal 8-view plots. Is this normal? If it's abnormal which place could be the problem?
![88d94ceb9146320c4dc5cbf84930c04](https://github.com/3DTopia/LGM/assets/77476098/1ad59dce-cd19-4e2e-adc6-b42689e3b529)
![4bb7ef1aa4d7d60af7f98de7422d424](https://github.com/3DTopia/LGM/assets/77476098/df7558db-1947-483e-9628-2734fb583db8)

**Comment by ashawkey** [comment]
As answered in the email, this may be caused by wrong camera poses.
