### ISSUE TITLE
How does LGM support `fp16` training for `diff-gaussian-rasterization`?

### ISSUE THREAD

**Issue by thucz** [3DTopia/LGM#58]
Hi! I wonder which code you revised to support `fp16` training in the original `diff-gaussian-rasterization`?

**Comment by yifanlu0227** [comment]
Hi, have you figured it out?

**Comment by thucz** [comment]
In fact, their diff-gaussian-rasterization does not support fp16. they use float32 in this module and fp16 in their neural networks.
