### ISSUE TITLE
Problem about dataset

### ISSUE THREAD

**Issue by LiaoLW** [3DTopia/LGM#75]
Thank you for your work!
I'm confusing about the implementation of dataset. According to LGM/objaverse_filter,  these datasets requires images and extra camera pose for LGM, is there any guide to reproduce your pre-process?

**Comment by RyanNg1403** [comment]
I guessed you solved the problem, can you tell how you did, thank you a lot!

**Comment by lcc815** [comment]
Can any one give an instruction?
